### PR TITLE
Taking out unused images, Issue #130

### PR DESCRIPTION
**Pull request by lskrabonja**

### CODE REVIEW

**Comment by roblarsen** [comment]
( @rcherny,  dude, do they have you locked in a cage over there?)

**Comment by amcintyre-cs** [comment]
I'm still here, too! Hi everybody!

**Comment by roblarsen** [comment]
Adam has a corporate username now!

**Comment by rcherny** [comment]
Clearly he sold out ;-)

And no, not a cage, just chained to a desk :-)

**Pull request merged**
